language: c
dist: trusty
sudo: required
env:
  # EMULATOR=simh
  # EMULATOR=klh10 MACSYMA=no
  - EMULATOR=sims MACSYMA=no
install: sh -ex build/dependencies.sh install_${TRAVIS_OS_NAME:-linux}
script: make
notifications:
  email: lars@nocrew.org
