language: c
dist: trusty
sudo: required
env:
  - EMULATOR=simh BASICS=yes
  - EMULATOR=klh10 BASICS=yes
  - EMULATOR=sims BASICS=yes
install: sh -ex build/dependencies.sh install_${TRAVIS_OS_NAME:-linux}
script: make check-dirs all
deploy:
  provider: s3
  access_key_id: "$AWS_ID"
  secret_access_key: "$AWS_SECRET"
  bucket: "$S3_BUCKET"
  skip_cleanup: true
  local_dir: out
  acl: public_read
  on:
    branch: master
after_deploy:
  - build/deploy.sh
notifications:
  email: lars@nocrew.org
